#ifndef DIO_CFG_H
#define DIO_CFG_H

#define DIO_BASE_ADDRESS              (0xFFFF2000U)

#define DIO_A_REGISTER_OFFSET         (DIO_BASE_ADDRESS + 0x0000U)
#define DIO_B_REGISTER_OFFSET         (DIO_BASE_ADDRESS + 0x0200U)
#define DIO_C_REGISTER_OFFSET         (DIO_BASE_ADDRESS + 0x0400U)
#define DIO_D_REGISTER_OFFSET         (DIO_BASE_ADDRESS + 0x0600U)

#define DIO_GPER_REGISTER_OFFSET      (0x000U)
#define DIO_GPERS_REGISTER_OFFSET     (0x004U)
#define DIO_GPERC_REGISTER_OFFSET     (0x008U)
#define DIO_GPERT_REGISTER_OFFSET     (0x00CU)

#define DIO_ODER_REGISTER_OFFSET      (0x040U)
#define DIO_ODERS_REGISTER_OFFSET     (0x044U)
#define DIO_ODERC_REGISTER_OFFSET     (0x048U)
#define DIO_ODERT_REGISTER_OFFSET     (0x04CU)
#define DIO_OVR_REGISTER_OFFSET       (0x050U)
#define DIO_OVRS_REGISTER_OFFSET      (0x054U)
#define DIO_OVRC_REGISTER_OFFSET      (0x058U)
#define DIO_OVRT_REGISTER_OFFSET      (0x05CU)
#define DIO_PVR_REGISTER_OFFSET       (0x060U)

#endif
