#include "Port.h"

const Port_ConfigType Port_InitialConfiguration_s =
{
      {
            {
                  PORT_PA0,
                  GPIO_MODE,
                  PIN_OUTPUT,
                  PIN_LOW,
                  NO_PULLUP_PULLDOWN,
                  INTERRUPT_DISABLED,
                  GLITCH_FILTER_DISABLED,
                  OUTPUT_DRIVING_LOW
            },
            {
                  PORT_PA1,
                  PERIPHERAL_FUNC_G,
                  PIN_INPUT,
                  PIN_LOW,
                  NO_PULLUP_PULLDOWN,
                  INTERRUPT_DISABLED,
                  GLITCH_FILTER_DISABLED,
                  OUTPUT_DRIVING_LOW
            },

            {
                  PORT_PA2,
                  GPIO_MODE,
                  PIN_OUTPUT,
                  PIN_HIGH,
                  NO_PULLUP_PULLDOWN,
                  INTERRUPT_PIN_CHANGE,
                  GLITCH_FILTER_DISABLED,
                  OUTPUT_DRIVING_LOW
            },
            {
                  PORT_PA3,
                  GPIO_MODE,
                  PIN_INPUT,
                  PIN_LOW,
                  NO_PULLUP_PULLDOWN,
                  INTERRUPT_DISABLED,
                  GLITCH_FILTER_DISABLED,
                  OUTPUT_DRIVING_LOW
            },
            {
                  PORT_PA4,
                  GPIO_MODE,
                  PIN_OUTPUT,
                  PIN_LOW,
                  NO_PULLUP_PULLDOWN,
                  INTERRUPT_DISABLED,
                  GLITCH_FILTER_DISABLED,
                  OUTPUT_DRIVING_LOW
            },
            {
                  PORT_PA5,
                  GPIO_MODE,
                  PIN_OUTPUT,
                  PIN_LOW,
                  NO_PULLUP_PULLDOWN,
                  INTERRUPT_DISABLED,
                  GLITCH_FILTER_DISABLED,
                  OUTPUT_DRIVING_LOW
            },
            {
                  PORT_PA6,
                  GPIO_MODE,
                  PIN_OUTPUT,
                  PIN_LOW,
                  NO_PULLUP_PULLDOWN,
                  INTERRUPT_DISABLED,
                  GLITCH_FILTER_DISABLED,
                  OUTPUT_DRIVING_LOW
            },
            {
                  PORT_PA7,
                  GPIO_MODE,
                  PIN_OUTPUT,
                  PIN_LOW,
                  NO_PULLUP_PULLDOWN,
                  INTERRUPT_DISABLED,
                  GLITCH_FILTER_DISABLED,
                  OUTPUT_DRIVING_LOW
            },
            {
                  PORT_PA8,
                  GPIO_MODE,
                  PIN_OUTPUT,
                  PIN_LOW,
                  NO_PULLUP_PULLDOWN,
                  INTERRUPT_DISABLED,
                  GLITCH_FILTER_DISABLED,
                  OUTPUT_DRIVING_LOW
            },
            {
                  PORT_PA9,
                  GPIO_MODE,
                  PIN_OUTPUT,
                  PIN_LOW,
                  NO_PULLUP_PULLDOWN,
                  INTERRUPT_DISABLED,
                  GLITCH_FILTER_DISABLED,
                  OUTPUT_DRIVING_LOW
            },
            {
                  PORT_PA16,
                  GPIO_MODE,
                  PIN_OUTPUT,
                  PIN_LOW,
                  NO_PULLUP_PULLDOWN,
                  INTERRUPT_DISABLED,
                  GLITCH_FILTER_DISABLED,
                  OUTPUT_DRIVING_LOW
            },
            {
                  PORT_PA19,
                  GPIO_MODE,
                  PIN_OUTPUT,
                  PIN_LOW,
                  NO_PULLUP_PULLDOWN,
                  INTERRUPT_DISABLED,
                  GLITCH_FILTER_DISABLED,
                  OUTPUT_DRIVING_LOW
            },
            {
                  PORT_PA20,
                  GPIO_MODE,
                  PIN_OUTPUT,
                  PIN_LOW,
                  NO_PULLUP_PULLDOWN,
                  INTERRUPT_DISABLED,
                  GLITCH_FILTER_DISABLED,
                  OUTPUT_DRIVING_LOW
            },
            {
                  PORT_PA21,
                  GPIO_MODE,
                  PIN_OUTPUT,
                  PIN_LOW,
                  NO_PULLUP_PULLDOWN,
                  INTERRUPT_DISABLED,
                  GLITCH_FILTER_DISABLED,
                  OUTPUT_DRIVING_LOW
            },
            {
                  PORT_PA22,
                  GPIO_MODE,
                  PIN_OUTPUT,
                  PIN_LOW,
                  NO_PULLUP_PULLDOWN,
                  INTERRUPT_DISABLED,
                  GLITCH_FILTER_DISABLED,
                  OUTPUT_DRIVING_LOW
            },
            {
                  PORT_PA23,
                  GPIO_MODE,
                  PIN_OUTPUT,
                  PIN_LOW,
                  NO_PULLUP_PULLDOWN,
                  INTERRUPT_DISABLED,
                  GLITCH_FILTER_DISABLED,
                  OUTPUT_DRIVING_LOW
            },
            {
                  PORT_PB0,
                  GPIO_MODE,
                  PIN_OUTPUT,
                  PIN_LOW,
                  NO_PULLUP_PULLDOWN,
                  INTERRUPT_DISABLED,
                  GLITCH_FILTER_DISABLED,
                  OUTPUT_DRIVING_LOW
            },
            {
                  PORT_PB1,
                  GPIO_MODE,
                  PIN_OUTPUT,
                  PIN_LOW,
                  NO_PULLUP_PULLDOWN,
                  INTERRUPT_DISABLED,
                  GLITCH_FILTER_DISABLED,
                  OUTPUT_DRIVING_LOW
            },
            {
                  PORT_PB30,
                  GPIO_MODE,
                  PIN_OUTPUT,
                  PIN_LOW,
                  NO_PULLUP_PULLDOWN,
                  INTERRUPT_DISABLED,
                  GLITCH_FILTER_DISABLED,
                  OUTPUT_DRIVING_LOW
            },
            {
                  PORT_PB31,
                  GPIO_MODE,
                  PIN_OUTPUT,
                  PIN_LOW,
                  NO_PULLUP_PULLDOWN,
                  INTERRUPT_DISABLED,
                  GLITCH_FILTER_DISABLED,
                  OUTPUT_DRIVING_LOW
            },
            {
                  PORT_PC2,
                  GPIO_MODE,
                  PIN_OUTPUT,
                  PIN_LOW,
                  NO_PULLUP_PULLDOWN,
                  INTERRUPT_DISABLED,
                  GLITCH_FILTER_DISABLED,
                  OUTPUT_DRIVING_LOW
            },
            {
                  PORT_PC3,
                  GPIO_MODE,
                  PIN_OUTPUT,
                  PIN_LOW,
                  NO_PULLUP_PULLDOWN,
                  INTERRUPT_DISABLED,
                  GLITCH_FILTER_DISABLED,
                  OUTPUT_DRIVING_LOW
            },
            {
                  PORT_PC4,
                  GPIO_MODE,
                  PIN_OUTPUT,
                  PIN_LOW,
                  NO_PULLUP_PULLDOWN,
                  INTERRUPT_DISABLED,
                  GLITCH_FILTER_DISABLED,
                  OUTPUT_DRIVING_LOW
            },
            {
                  PORT_PC5,
                  GPIO_MODE,
                  PIN_OUTPUT,
                  PIN_LOW,
                  NO_PULLUP_PULLDOWN,
                  INTERRUPT_DISABLED,
                  GLITCH_FILTER_DISABLED,
                  OUTPUT_DRIVING_LOW
            },
            {
                  PORT_PC15,
                  GPIO_MODE,
                  PIN_OUTPUT,
                  NO_PULLUP_PULLDOWN,
                  INTERRUPT_DISABLED,
                  GLITCH_FILTER_DISABLED,
                  OUTPUT_DRIVING_LOW
            },
            {
                  PORT_PC16,
                  GPIO_MODE,
                  PIN_OUTPUT,
                  PIN_LOW,
                  NO_PULLUP_PULLDOWN,
                  INTERRUPT_DISABLED,
                  GLITCH_FILTER_DISABLED,
                  OUTPUT_DRIVING_LOW
            },
            {
                  PORT_PC17,
                  GPIO_MODE,
                  PIN_OUTPUT,
                  PIN_LOW,
                  NO_PULLUP_PULLDOWN,
                  INTERRUPT_DISABLED,
                  GLITCH_FILTER_DISABLED,
                  OUTPUT_DRIVING_LOW
            },
            {
                  PORT_PC18,
                  GPIO_MODE,
                  PIN_OUTPUT,
                  PIN_LOW,
                  NO_PULLUP_PULLDOWN,
                  INTERRUPT_DISABLED,
                  GLITCH_FILTER_DISABLED,
                  OUTPUT_DRIVING_LOW
            },
            {
                  PORT_PC19,
                  GPIO_MODE,
                  PIN_OUTPUT,
                  PIN_LOW,
                  NO_PULLUP_PULLDOWN,
                  INTERRUPT_DISABLED,
                  GLITCH_FILTER_DISABLED,
                  OUTPUT_DRIVING_LOW
            },
            {
                  PORT_PC20,
                  GPIO_MODE,
                  PIN_OUTPUT,
                  PIN_LOW,
                  NO_PULLUP_PULLDOWN,
                  INTERRUPT_DISABLED,
                  GLITCH_FILTER_DISABLED,
                  OUTPUT_DRIVING_LOW
            },
            {
                  PORT_PC21,
                  GPIO_MODE,
                  PIN_OUTPUT,
                  PIN_LOW,
                  NO_PULLUP_PULLDOWN,
                  INTERRUPT_DISABLED,
                  GLITCH_FILTER_DISABLED,
                  OUTPUT_DRIVING_LOW
            },
            {
                  PORT_PC22,
                  GPIO_MODE,
                  PIN_OUTPUT,
                  PIN_LOW,
                  NO_PULLUP_PULLDOWN,
                  INTERRUPT_DISABLED,
                  GLITCH_FILTER_DISABLED,
                  OUTPUT_DRIVING_LOW
            },
            {
                  PORT_PD0,
                  GPIO_MODE,
                  PIN_OUTPUT,
                  PIN_LOW,
                  NO_PULLUP_PULLDOWN,
                  INTERRUPT_DISABLED,
                  GLITCH_FILTER_DISABLED,
                  OUTPUT_DRIVING_LOW
            },
            {
                  PORT_PD1,
                  GPIO_MODE,
                  PIN_OUTPUT,
                  PIN_LOW,
                  NO_PULLUP_PULLDOWN,
                  INTERRUPT_DISABLED,
                  GLITCH_FILTER_DISABLED,
                  OUTPUT_DRIVING_LOW
            },
            {
                  PORT_PD2,
                  GPIO_MODE,
                  PIN_OUTPUT,
                  PIN_LOW,
                  NO_PULLUP_PULLDOWN,
                  INTERRUPT_DISABLED,
                  GLITCH_FILTER_DISABLED,
                  OUTPUT_DRIVING_LOW
            },
            {
                  PORT_PD3,
                  GPIO_MODE,
                  PIN_OUTPUT,
                  PIN_LOW,
                  NO_PULLUP_PULLDOWN,
                  INTERRUPT_DISABLED,
                  GLITCH_FILTER_DISABLED,
                  OUTPUT_DRIVING_LOW
            },
            {
                  PORT_PD11,
                  GPIO_MODE,
                  PIN_OUTPUT,
                  PIN_LOW,
                  NO_PULLUP_PULLDOWN,
                  INTERRUPT_DISABLED,
                  GLITCH_FILTER_DISABLED,
                  OUTPUT_DRIVING_LOW
            },
            {
                  PORT_PD12,
                  GPIO_MODE,
                  PIN_OUTPUT,
                  PIN_LOW,
                  NO_PULLUP_PULLDOWN,
                  INTERRUPT_DISABLED,
                  GLITCH_FILTER_DISABLED,
                  OUTPUT_DRIVING_LOW
            },
            {
                  PORT_PD13,
                  GPIO_MODE,
                  PIN_OUTPUT,
                  PIN_LOW,
                  NO_PULLUP_PULLDOWN,
                  INTERRUPT_DISABLED,
                  GLITCH_FILTER_DISABLED,
                  OUTPUT_DRIVING_LOW
            },
            {
                  PORT_PD14,
                  GPIO_MODE,
                  PIN_OUTPUT,
                  PIN_LOW,
                  NO_PULLUP_PULLDOWN,
                  INTERRUPT_DISABLED,
                  GLITCH_FILTER_DISABLED,
                  OUTPUT_DRIVING_LOW
            },
            {
                  PORT_PD21,
                  GPIO_MODE,
                  PIN_OUTPUT,
                  PIN_LOW,
                  NO_PULLUP_PULLDOWN,
                  INTERRUPT_DISABLED,
                  GLITCH_FILTER_DISABLED,
                  OUTPUT_DRIVING_LOW
            },
            {
                  PORT_PD27,
                  GPIO_MODE,
                  PIN_OUTPUT,
                  PIN_LOW,
                  NO_PULLUP_PULLDOWN,
                  INTERRUPT_DISABLED,
                  GLITCH_FILTER_DISABLED,
                  OUTPUT_DRIVING_LOW
            },
            {
                  PORT_PD28,
                  GPIO_MODE,
                  PIN_OUTPUT,
                  PIN_LOW,
                  NO_PULLUP_PULLDOWN,
                  INTERRUPT_DISABLED,
                  GLITCH_FILTER_DISABLED,
                  OUTPUT_DRIVING_LOW
            },
            {
                  PORT_PD29,
                  GPIO_MODE,
                  PIN_OUTPUT,
                  PIN_LOW,
                  NO_PULLUP_PULLDOWN,
                  INTERRUPT_DISABLED,
                  GLITCH_FILTER_DISABLED,
                  OUTPUT_DRIVING_LOW
            },
            {
                  PORT_PD30,
                  GPIO_MODE,
                  PIN_OUTPUT,
                  PIN_LOW,
                  NO_PULLUP_PULLDOWN,
                  INTERRUPT_DISABLED,
                  GLITCH_FILTER_DISABLED,
                  OUTPUT_DRIVING_LOW
            },
            {
                  PORT_PD31,
                  GPIO_MODE,
                  PIN_OUTPUT,
                  PIN_LOW,
                  NO_PULLUP_PULLDOWN,
                  INTERRUPT_DISABLED,
                  GLITCH_FILTER_DISABLED,
                  OUTPUT_DRIVING_LOW
            },
      }
};





const void *Port_GetLcfgData(void)
{
   return ((void*) &Port_InitialConfiguration_s);
}
