#include "Port.h"

const Port_ConfigType Port_InitialConfiguration_s =
{
      {
            {
                  DIO_CHANNEL_PA0,
                  GPIO_MODE,
                  PIN_OUTPUT,
                  PIN_LOW,
                  NO_PULLUP_PULLDOWN,
                  INTERRUPT_DISABLED,
                  GLITCH_FILTER_DISABLED,
                  OUTPUT_DRIVING_LOW
            },
            {
                  DIO_CHANNEL_PA1,
                  PERIPHERAL_FUNC_G,
                  PIN_INPUT,
                  PIN_LOW,
                  NO_PULLUP_PULLDOWN,
                  INTERRUPT_DISABLED,
                  GLITCH_FILTER_DISABLED,
                  OUTPUT_DRIVING_LOW
            },

            {
                  DIO_CHANNEL_PA2,
                  GPIO_MODE,
                  PIN_OUTPUT,
                  PIN_HIGH,
                  NO_PULLUP_PULLDOWN,
                  INTERRUPT_PIN_CHANGE,
                  GLITCH_FILTER_DISABLED,
                  OUTPUT_DRIVING_LOW
            },
            {
                  DIO_CHANNEL_PA3,
                  GPIO_MODE,
                  PIN_INPUT,
                  PIN_LOW,
                  NO_PULLUP_PULLDOWN,
                  INTERRUPT_DISABLED,
                  GLITCH_FILTER_DISABLED,
                  OUTPUT_DRIVING_LOW
            },
            {
                  DIO_CHANNEL_PA4,
                  GPIO_MODE,
                  PIN_OUTPUT,
                  PIN_LOW,
                  NO_PULLUP_PULLDOWN,
                  INTERRUPT_DISABLED,
                  GLITCH_FILTER_DISABLED,
                  OUTPUT_DRIVING_LOW
            },
            {
                  DIO_CHANNEL_PA5,
                  GPIO_MODE,
                  PIN_OUTPUT,
                  PIN_LOW,
                  NO_PULLUP_PULLDOWN,
                  INTERRUPT_DISABLED,
                  GLITCH_FILTER_DISABLED,
                  OUTPUT_DRIVING_LOW
            },
            {
                  DIO_CHANNEL_PA6,
                  GPIO_MODE,
                  PIN_OUTPUT,
                  PIN_LOW,
                  NO_PULLUP_PULLDOWN,
                  INTERRUPT_DISABLED,
                  GLITCH_FILTER_DISABLED,
                  OUTPUT_DRIVING_LOW
            },
            {
                  DIO_CHANNEL_PA7,
                  GPIO_MODE,
                  PIN_OUTPUT,
                  PIN_LOW,
                  NO_PULLUP_PULLDOWN,
                  INTERRUPT_DISABLED,
                  GLITCH_FILTER_DISABLED,
                  OUTPUT_DRIVING_LOW
            },
            {
                  DIO_CHANNEL_PA8,
                  GPIO_MODE,
                  PIN_OUTPUT,
                  PIN_LOW,
                  NO_PULLUP_PULLDOWN,
                  INTERRUPT_DISABLED,
                  GLITCH_FILTER_DISABLED,
                  OUTPUT_DRIVING_LOW
            },
            {
                  DIO_CHANNEL_PA9,
                  GPIO_MODE,
                  PIN_OUTPUT,
                  PIN_LOW,
                  NO_PULLUP_PULLDOWN,
                  INTERRUPT_DISABLED,
                  GLITCH_FILTER_DISABLED,
                  OUTPUT_DRIVING_LOW
            },
            {
                  DIO_CHANNEL_PA16,
                  GPIO_MODE,
                  PIN_OUTPUT,
                  PIN_LOW,
                  NO_PULLUP_PULLDOWN,
                  INTERRUPT_DISABLED,
                  GLITCH_FILTER_DISABLED,
                  OUTPUT_DRIVING_LOW
            },
            {
                  DIO_CHANNEL_PA19,
                  GPIO_MODE,
                  PIN_OUTPUT,
                  PIN_LOW,
                  NO_PULLUP_PULLDOWN,
                  INTERRUPT_DISABLED,
                  GLITCH_FILTER_DISABLED,
                  OUTPUT_DRIVING_LOW
            },
            {
                  DIO_CHANNEL_PA20,
                  GPIO_MODE,
                  PIN_OUTPUT,
                  PIN_LOW,
                  NO_PULLUP_PULLDOWN,
                  INTERRUPT_DISABLED,
                  GLITCH_FILTER_DISABLED,
                  OUTPUT_DRIVING_LOW
            },
            {
                  DIO_CHANNEL_PA21,
                  GPIO_MODE,
                  PIN_OUTPUT,
                  PIN_LOW,
                  NO_PULLUP_PULLDOWN,
                  INTERRUPT_DISABLED,
                  GLITCH_FILTER_DISABLED,
                  OUTPUT_DRIVING_LOW
            },
            {
                  DIO_CHANNEL_PA22,
                  GPIO_MODE,
                  PIN_OUTPUT,
                  PIN_LOW,
                  NO_PULLUP_PULLDOWN,
                  INTERRUPT_DISABLED,
                  GLITCH_FILTER_DISABLED,
                  OUTPUT_DRIVING_LOW
            },
            {
                  DIO_CHANNEL_PA23,
                  GPIO_MODE,
                  PIN_OUTPUT,
                  PIN_LOW,
                  NO_PULLUP_PULLDOWN,
                  INTERRUPT_DISABLED,
                  GLITCH_FILTER_DISABLED,
                  OUTPUT_DRIVING_LOW
            },
            {
                  DIO_CHANNEL_PB0,
                  GPIO_MODE,
                  PIN_OUTPUT,
                  PIN_LOW,
                  NO_PULLUP_PULLDOWN,
                  INTERRUPT_DISABLED,
                  GLITCH_FILTER_DISABLED,
                  OUTPUT_DRIVING_LOW
            },
            {
                  DIO_CHANNEL_PB1,
                  GPIO_MODE,
                  PIN_OUTPUT,
                  PIN_LOW,
                  NO_PULLUP_PULLDOWN,
                  INTERRUPT_DISABLED,
                  GLITCH_FILTER_DISABLED,
                  OUTPUT_DRIVING_LOW
            },
            {
                  DIO_CHANNEL_PB30,
                  GPIO_MODE,
                  PIN_OUTPUT,
                  PIN_LOW,
                  NO_PULLUP_PULLDOWN,
                  INTERRUPT_DISABLED,
                  GLITCH_FILTER_DISABLED,
                  OUTPUT_DRIVING_LOW
            },
            {
                  DIO_CHANNEL_PB31,
                  GPIO_MODE,
                  PIN_OUTPUT,
                  PIN_LOW,
                  NO_PULLUP_PULLDOWN,
                  INTERRUPT_DISABLED,
                  GLITCH_FILTER_DISABLED,
                  OUTPUT_DRIVING_LOW
            },
            {
                  DIO_CHANNEL_PC2,
                  GPIO_MODE,
                  PIN_OUTPUT,
                  PIN_LOW,
                  NO_PULLUP_PULLDOWN,
                  INTERRUPT_DISABLED,
                  GLITCH_FILTER_DISABLED,
                  OUTPUT_DRIVING_LOW
            },
            {
                  DIO_CHANNEL_PC3,
                  GPIO_MODE,
                  PIN_OUTPUT,
                  PIN_LOW,
                  NO_PULLUP_PULLDOWN,
                  INTERRUPT_DISABLED,
                  GLITCH_FILTER_DISABLED,
                  OUTPUT_DRIVING_LOW
            },
            {
                  DIO_CHANNEL_PC4,
                  GPIO_MODE,
                  PIN_OUTPUT,
                  PIN_LOW,
                  NO_PULLUP_PULLDOWN,
                  INTERRUPT_DISABLED,
                  GLITCH_FILTER_DISABLED,
                  OUTPUT_DRIVING_LOW
            },
            {
                  DIO_CHANNEL_PC5,
                  GPIO_MODE,
                  PIN_OUTPUT,
                  PIN_LOW,
                  NO_PULLUP_PULLDOWN,
                  INTERRUPT_DISABLED,
                  GLITCH_FILTER_DISABLED,
                  OUTPUT_DRIVING_LOW
            },
            {
                  DIO_CHANNEL_PC15,
                  GPIO_MODE,
                  PIN_OUTPUT,
                  NO_PULLUP_PULLDOWN,
                  INTERRUPT_DISABLED,
                  GLITCH_FILTER_DISABLED,
                  OUTPUT_DRIVING_LOW
            },
            {
                  DIO_CHANNEL_PC16,
                  GPIO_MODE,
                  PIN_OUTPUT,
                  PIN_LOW,
                  NO_PULLUP_PULLDOWN,
                  INTERRUPT_DISABLED,
                  GLITCH_FILTER_DISABLED,
                  OUTPUT_DRIVING_LOW
            },
            {
                  DIO_CHANNEL_PC17,
                  GPIO_MODE,
                  PIN_OUTPUT,
                  PIN_LOW,
                  NO_PULLUP_PULLDOWN,
                  INTERRUPT_DISABLED,
                  GLITCH_FILTER_DISABLED,
                  OUTPUT_DRIVING_LOW
            },
            {
                  DIO_CHANNEL_PC18,
                  GPIO_MODE,
                  PIN_OUTPUT,
                  PIN_LOW,
                  NO_PULLUP_PULLDOWN,
                  INTERRUPT_DISABLED,
                  GLITCH_FILTER_DISABLED,
                  OUTPUT_DRIVING_LOW
            },
            {
                  DIO_CHANNEL_PC19,
                  GPIO_MODE,
                  PIN_OUTPUT,
                  PIN_LOW,
                  NO_PULLUP_PULLDOWN,
                  INTERRUPT_DISABLED,
                  GLITCH_FILTER_DISABLED,
                  OUTPUT_DRIVING_LOW
            },
            {
                  DIO_CHANNEL_PC20,
                  GPIO_MODE,
                  PIN_OUTPUT,
                  PIN_LOW,
                  NO_PULLUP_PULLDOWN,
                  INTERRUPT_DISABLED,
                  GLITCH_FILTER_DISABLED,
                  OUTPUT_DRIVING_LOW
            },
            {
                  DIO_CHANNEL_PC21,
                  GPIO_MODE,
                  PIN_OUTPUT,
                  PIN_LOW,
                  NO_PULLUP_PULLDOWN,
                  INTERRUPT_DISABLED,
                  GLITCH_FILTER_DISABLED,
                  OUTPUT_DRIVING_LOW
            },
            {
                  DIO_CHANNEL_PC22,
                  GPIO_MODE,
                  PIN_OUTPUT,
                  PIN_LOW,
                  NO_PULLUP_PULLDOWN,
                  INTERRUPT_DISABLED,
                  GLITCH_FILTER_DISABLED,
                  OUTPUT_DRIVING_LOW
            },
            {
                  DIO_CHANNEL_PD0,
                  GPIO_MODE,
                  PIN_OUTPUT,
                  PIN_LOW,
                  NO_PULLUP_PULLDOWN,
                  INTERRUPT_DISABLED,
                  GLITCH_FILTER_DISABLED,
                  OUTPUT_DRIVING_LOW
            },
            {
                  DIO_CHANNEL_PD1,
                  GPIO_MODE,
                  PIN_OUTPUT,
                  PIN_LOW,
                  NO_PULLUP_PULLDOWN,
                  INTERRUPT_DISABLED,
                  GLITCH_FILTER_DISABLED,
                  OUTPUT_DRIVING_LOW
            },
            {
                  DIO_CHANNEL_PD2,
                  GPIO_MODE,
                  PIN_OUTPUT,
                  PIN_LOW,
                  NO_PULLUP_PULLDOWN,
                  INTERRUPT_DISABLED,
                  GLITCH_FILTER_DISABLED,
                  OUTPUT_DRIVING_LOW
            },
            {
                  DIO_CHANNEL_PD3,
                  GPIO_MODE,
                  PIN_OUTPUT,
                  PIN_LOW,
                  NO_PULLUP_PULLDOWN,
                  INTERRUPT_DISABLED,
                  GLITCH_FILTER_DISABLED,
                  OUTPUT_DRIVING_LOW
            },
            {
                  DIO_CHANNEL_PD11,
                  GPIO_MODE,
                  PIN_OUTPUT,
                  PIN_LOW,
                  NO_PULLUP_PULLDOWN,
                  INTERRUPT_DISABLED,
                  GLITCH_FILTER_DISABLED,
                  OUTPUT_DRIVING_LOW
            },
            {
                  DIO_CHANNEL_PD12,
                  GPIO_MODE,
                  PIN_OUTPUT,
                  PIN_LOW,
                  NO_PULLUP_PULLDOWN,
                  INTERRUPT_DISABLED,
                  GLITCH_FILTER_DISABLED,
                  OUTPUT_DRIVING_LOW
            },
            {
                  DIO_CHANNEL_PD13,
                  GPIO_MODE,
                  PIN_OUTPUT,
                  PIN_LOW,
                  NO_PULLUP_PULLDOWN,
                  INTERRUPT_DISABLED,
                  GLITCH_FILTER_DISABLED,
                  OUTPUT_DRIVING_LOW
            },
            {
                  DIO_CHANNEL_PD14,
                  GPIO_MODE,
                  PIN_OUTPUT,
                  PIN_LOW,
                  NO_PULLUP_PULLDOWN,
                  INTERRUPT_DISABLED,
                  GLITCH_FILTER_DISABLED,
                  OUTPUT_DRIVING_LOW
            },
            {
                  DIO_CHANNEL_PD21,
                  GPIO_MODE,
                  PIN_OUTPUT,
                  PIN_LOW,
                  NO_PULLUP_PULLDOWN,
                  INTERRUPT_DISABLED,
                  GLITCH_FILTER_DISABLED,
                  OUTPUT_DRIVING_LOW
            },
            {
                  DIO_CHANNEL_PD27,
                  GPIO_MODE,
                  PIN_OUTPUT,
                  PIN_LOW,
                  NO_PULLUP_PULLDOWN,
                  INTERRUPT_DISABLED,
                  GLITCH_FILTER_DISABLED,
                  OUTPUT_DRIVING_LOW
            },
            {
                  DIO_CHANNEL_PD28,
                  GPIO_MODE,
                  PIN_OUTPUT,
                  PIN_LOW,
                  NO_PULLUP_PULLDOWN,
                  INTERRUPT_DISABLED,
                  GLITCH_FILTER_DISABLED,
                  OUTPUT_DRIVING_LOW
            },
            {
                  DIO_CHANNEL_PD29,
                  GPIO_MODE,
                  PIN_OUTPUT,
                  PIN_LOW,
                  NO_PULLUP_PULLDOWN,
                  INTERRUPT_DISABLED,
                  GLITCH_FILTER_DISABLED,
                  OUTPUT_DRIVING_LOW
            },
            {
                  DIO_CHANNEL_PD30,
                  GPIO_MODE,
                  PIN_OUTPUT,
                  PIN_LOW,
                  NO_PULLUP_PULLDOWN,
                  INTERRUPT_DISABLED,
                  GLITCH_FILTER_DISABLED,
                  OUTPUT_DRIVING_LOW
            },
            {
                  DIO_CHANNEL_PD31,
                  GPIO_MODE,
                  PIN_OUTPUT,
                  PIN_LOW,
                  NO_PULLUP_PULLDOWN,
                  INTERRUPT_DISABLED,
                  GLITCH_FILTER_DISABLED,
                  OUTPUT_DRIVING_LOW
            },
      }
};





const void *Port_GetLcfgData(void)
{
   return ((void*) &Port_InitialConfiguration_s);
}
